
language: java
# Building a Java project
#   https://docs.travis-ci.com/user/languages/java
#
# how to install and set jdk on travis:
# - Testing Against Multiple JDKs
#   https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
# - JVM images
#   https://docs.travis-ci.com/user/reference/trusty/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-images
# - Customizing the Build / Build Matrix
#   https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

dist: trusty

addons:
  apt:
    packages:
      - openjdk-6-jdk

branches:
  except:
    - appveyor

# Job Lifecycle
#   https://docs.travis-ci.com/user/job-lifecycle/

before_install:
  # workaround for "buffer overflow detected" problem of openjdk:
  #     https://github.com/travis-ci/travis-ci/issues/5227
  # borrow from https://github.com/miguno/kafka-storm-starter/blob/01dd534263eb867304c06cd2a72f640da1bd9367/.travis.yml
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

  # output env info
  - ls -la
  - ls -l /usr/lib/jvm && ls /usr/lib/jvm/*
  - echo -e "JAVA_HOME=$JAVA_HOME\nPATH=$PATH\nSHELL=$SHELL"

install:
  - pip install --user codecov

script:
  - ./scripts/integration-test.sh

after_success:
  # codecov
  - ./scripts/codecov.sh

after_script:
  - git status --ignored

before_cache:
  # clear TTL maven self install
  - rm -rf $HOME/.m2/repository/com/alibaba/transmittable-thread-local
# Caching Dependencies and Directories
# https://docs.travis-ci.com/user/caching/
cache:
  - pip
  - directories:
    - $HOME/.m2
    - $HOME/.sdkman
    - $HOME/.cache/pip
